# Numpy

In [2]:
import numpy as np

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array (my_list)

array([1, 2, 3])

In [4]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
my_matrix[0]

[1, 2, 3]

In [6]:
my_matrix[0][1]

2

In [7]:
my_matrix[2][0]

7

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
[i for i in range(0,10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
[i for i in range(0,10,3)]
#jump by three

[0, 3, 6, 9]

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## zeros and ones

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((3,5))
#3 vertical, 5 horizontal

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.zeros(shape=4)

array([0., 0., 0., 0.])

In [20]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Linspace

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [24]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [25]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [26]:
[i for i in range(11)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## Eye

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.eye(1)

array([[1.]])

In [29]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

## Random
### Rand

In [3]:
np.random.rand(2)
#produces 2 uniform random numbers between 0 and 1

array([0.04975415, 0.55636927])

In [31]:
np.random.rand(5)

array([0.0056842 , 0.49339426, 0.401911  , 0.23472098, 0.19170551])

In [32]:
np.random.rand(5,5)

array([[0.20847043, 0.97476905, 0.65898934, 0.9847419 , 0.62729379],
       [0.11934066, 0.83074189, 0.9620566 , 0.62909975, 0.53817666],
       [0.00882036, 0.46719718, 0.14036681, 0.29162781, 0.02070348],
       [0.3721746 , 0.163435  , 0.14757759, 0.72438397, 0.03561176],
       [0.50859684, 0.83131008, 0.77175731, 0.81124762, 0.23367743]])

### Randn

In [33]:
np.random.randn(2)

array([ 0.06122217, -0.98826204])

In [34]:
np.random.randn(5)

array([-0.07007156,  0.81289228,  0.63992522,  0.53399956, -0.53867979])

In [35]:
np.random.randn(5,5)

array([[-0.66393964, -0.78203623, -0.64667247, -0.18198617, -0.50655364],
       [-1.21471853,  0.96526794, -0.36384234,  1.61409884, -0.79916466],
       [ 0.31600217,  0.57382689,  2.41147061,  0.09302118, -0.44352823],
       [-0.88037284, -0.34785633, -0.18155121,  1.7986409 , -2.66131091],
       [-0.66654987,  0.1463797 ,  1.74787517,  0.88258611,  0.03294247]])

### Randint

In [36]:
np.random.randint(1,2)

1

In [ ]:
x = random.randint(100)
print(x)

In [37]:
np.random.randint(1,100)

37

In [38]:
np.random.randint(1,100)

94

In [39]:
np.random.randint(1,100,10)

array([50, 44, 67, 83, 75, 27,  8, 70, 56, 61])

In [40]:
np.random.randint(1,100,10)

array([88, 92,  4, 11, 50, 69, 19, 68, 80, 93])

In [41]:
np.random.seed(1)
np.random.randint(1,100,10)

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [42]:
np.random.seed(1)
np.random.randint(1,100,10)

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [43]:
arr=np.arange(25)
renarr=np.random.randint(0,50,10)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
renarr

array([12,  7, 45,  6, 25, 20, 37, 18, 20, 11])

### Choice

In [ ]:
x = random.choice([3, 5, 7, 9])

print(x)

In [ ]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

### Reshape

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)