In [12]:
from numpy import random
import numpy as np

In [2]:
x = random.randint(100)
print(x)

67


In [3]:
x = random.rand()

print(x)

0.04516513357467522


In [6]:
x = random.rand(5)

print(x)

[0.15644868 0.84015717 0.93764823 0.2481087  0.95816243]


In [7]:
x = random.rand(3, 5)

print(x)

[[0.06697035 0.91822347 0.05754775 0.40005134 0.55636704]
 [0.64380195 0.91073445 0.58867385 0.92339261 0.12646472]
 [0.95889969 0.87458963 0.78246723 0.73866881 0.13532465]]


In [4]:
x=random.randint(100, size=(5))

print(x)

[46 70 91 27 56]


In [5]:
x = random.randint(100, size=(3, 5))

print(x)

[[91 64 97  9 92]
 [26 11 80  8  4]
 [34 73 72 52  0]]


In [8]:
x = random.choice([3, 5, 7, 9])

print(x)

5


In [9]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 9 9 3 5]
 [3 7 5 5 7]
 [9 7 7 5 5]]


In [10]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 5 5 7 5 7 3 7 7 7 7 7 7 7 7 7 5 7 3 5 7 7 7 7 7 7 7 5 7 7 5 7 5 7 7
 7 3 5 5 5 7 5 7 7 7 7 5 7 7 7 5 3 7 7 7 5 7 3 7 7 3 7 7 7 7 7 3 5 5 7 7 5
 7 7 5 7 7 5 7 7 5 3 7 5 7 7 7 7 7 5 5 7 7 7 7 3 5 7]


In [11]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[5 7 7 7 7]
 [5 5 7 7 7]
 [5 3 7 5 7]]


In [13]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[1 5 3 4 2]


In [15]:
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))
print (arr)

[5 3 2 4 1]
[1 2 3 4 5]
